FROM gradle:jdk11 as builder

COPY . /app

WORKDIR /app

RUN gradle build


FROM openjdk:11-jre-slim

MAINTAINER William Brendaw <will@williambrendaw.com>

WORKDIR /app

COPY --from=builder /app/build/libs/invoice-0.0.1.jar /app/

CMD java -jar invoice-0.0.1.jar