server:
  port: 8100
  tomcat:
    max-threads: 200
    max-http-post-size: 2MB
    max-swallow-size: 2MB
    max-http-header-size: 8KB

endpoints:
  health:
    sensitive: false

logging:
  level:
    org.dojo.simple: DEBUG