server:
  port: 8300
  tomcat:
    max-threads: 200
    max-http-post-size: 2MB
    max-swallow-size: 2MB
    max-http-header-size: 8KB

endpoints:
  health:
    sensitive: false

logging:
  level:
    org.dojo.invoice: DEBUG


spring:
  client-service:
    url: ${CLIENT_SERVICE_URL:http://localhost:8200}
  data:
    mongodb:
      host: ${MONGODB_HOST:mongo}
      port: ${MONGODB_PORT:27017}